### ISSUE TITLE
"Add I_S and I_P sequence to part?" not calling `add_i_seqs` argument.

### ISSUE THREAD

**Issue by hainesm6** [LondonBiofoundry/basicsynbio_frontend#15]

**Comment by Benedict-Carling** [comment]
Hi @hainesm6 i've been looking at this and it seems the add_i_seq variable goes through successfully into the backend - It would be great if you could send me a file without i_P and i_S seq and show me what is should look like with I_seqs so i can try to make a reproducible example?

**Comment by hainesm6** [comment]
Thanks again for looking into this @Benedict-Carling. I've made a new branch in this repo `add-i-seqs`. In there you'll find a `sequences` directory with sfgp as fasta and genbank files. I tried both files previously and neither worked. There might also be another issue generally with importing fasta files. Let me how it goes.

**Comment by Benedict-Carling** [comment]
Solved
